Выполненные задания спринта №22 на проверку Яндекс-Практикумом
MSagGik/PlaylistMaker pull request #16
Opened 2024-08-25 12:36 UTC by MSagGik

Результаты выполнения практических заданий спринта №22 для проверки
(по требованиям Яндекс-Практикума в форме пулл-реквеста)

Настроил консистентность БД по модели "многие к многим"

С целью улучшения пользовательского опыта дополнительно добавил:
а) отображение информации нахождения трека в плейлисте/ах (если нужно будет убрать, поправлю);
б) поддержку на трёх языках русский/английский/китайский (на экране настроек могу ещё добавить возможность выбора языка приложения)

2024-08-26 03:51 UTC, DmitrijEgorow commented
- [ ] Приложение аварийно завершается

https://github.com/user-attachments/assets/d7171fd3-9c67-4774-a648-490f94a5ca8a


```
FATAL EXCEPTION: main  
Process: com.msaggik.playlistmaker, PID: 11018  
java.lang.IllegalStateException: Fragment CreatePlaylistFragment{15ad3ef} (8716b9ec-5695-42e6-9e8b-ee150886d1e7 id=0x7f0901c7 tag=d3889bd4-23be-41c4-bd4f-9a78f24a8978) does not have any arguments.  
at androidx.fragment.app.Fragment.requireArguments(Fragment.java:804)  
at com.msaggik.playlistmaker.create_playlist.presentation.ui.CreatePlaylistFragment$track$2.invoke(CreatePlaylistFragment.kt:59)  
at com.msaggik.playlistmaker.create_playlist.presentation.ui.CreatePlaylistFragment$track$2.invoke(CreatePlaylistFragment.kt:56)  
at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)  
at com.msaggik.playlistmaker.create_playlist.presentation.ui.CreatePlaylistFragment.getTrack(CreatePlaylistFragment.kt:56)  
at com.msaggik.playlistmaker.create_playlist.presentation.ui.CreatePlaylistFragment.access$getTrack(CreatePlaylistFragment.kt:35)  
at com.msaggik.playlistmaker.create_playlist.presentation.ui.CreatePlaylistFragment$listener$1.onClick(CreatePlaylistFragment.kt:179)  
at android.view.View.performClick(View.java:7892)  
at android.widget.TextView.performClick(TextView.java:16220)  
at android.view.View.performClickInternal(View.java:7869)  
at android.view.View.-[$Nest](tex://$Nest)mperformClickInternal(Unknown Source:0)  
at android.view.View$PerformClick.run(View.java:30891)  
at android.os.Handler.handleCallback(Handler.java:942)  
at android.os.Handler.dispatchMessage(Handler.java:99)
```

2024-08-26 03:52 UTC, DmitrijEgorow commented
- [ ] Достаточно выводить тост один раз

https://github.com/user-attachments/assets/ea556dea-7b0e-4783-bbcf-94ed0a681ce4

2024-08-26 03:54 UTC, DmitrijEgorow commented
- [ ] Этот трек в избранном (будто бы), но в списке избранного его нет. Если несколько раз подобавлять-поубирать, то в БД останется запись, а вот из списка UI он исчезнет

https://github.com/user-attachments/assets/d7227668-89aa-4579-a2b2-fe8a0a793b9d

2024-08-26 03:54 UTC, DmitrijEgorow commented
- [ ] Несоответствие дизайну для боковой кнопки
![Screenshot_20240826_102417](https://github.com/user-attachments/assets/5b613003-2ef2-4696-8d3e-62a2484914eb)

2024-08-26 03:55 UTC, DmitrijEgorow commented
- [ ] Список bottom sheet не соответствует дизайну
![Screenshot_20240826_102404](https://github.com/user-attachments/assets/28660c28-3ff2-4d80-a43d-3fcc23e762d2)

2024-08-26 03:55 UTC, DmitrijEgorow commented
- [ ] \n нужно убрать
![Screenshot_20240826_102251](https://github.com/user-attachments/assets/c0cf6e54-652d-4d96-b98e-06be2c58b1bf)

2024-08-26 03:57 UTC, DmitrijEgorow commented
- [ ] Фиолетовый текст не входит в цветовую палитру приложения
![Screenshot_20240826_102241](https://github.com/user-attachments/assets/4f23b1d7-3498-4d1b-9a6d-aa3aae202cb4)

2024-08-26 03:57 UTC, DmitrijEgorow commented
- [ ] Визуальные артефакты под заголовком
<img width="500" alt="Screenshot 2024-08-26 at 10 56 43" src="https://github.com/user-attachments/assets/bcbc4e0e-2aa6-4e1e-a9bc-606d09b2c8eb">

2024-08-26 04:07 UTC, DmitrijEgorow requested changes

2024-08-26 04:07 UTC, DmitrijEgorow commented on app/src/main/java/com/msaggik/playlistmaker/media/di/MediaModule.kt
> +        MediaMapper()
Почему mapper как single?

2024-08-26 04:07 UTC, DmitrijEgorow commented on app/src/main/java/com/msaggik/playlistmaker/media/presentation/ui/adapters/PlaylistWithTracksAdapter.kt
> +                else -> binding.root.context.getString(R.string.number_tracks_c, model.tracks.size)
Может, вынести как utils-функцию и переписпользовать или использовать string plurals?

2024-08-26 04:07 UTC, DmitrijEgorow commented on app/src/main/java/com/msaggik/playlistmaker/media/presentation/ui/fragments/PlaylistsFragment.kt
> +    }
Закомментированный код лучше не вливать в master

2024-08-26 04:07 UTC, DmitrijEgorow commented on app/src/main/java/com/msaggik/playlistmaker/player/data/repository_impl/TrackPlayerImpl.kt
>  class TrackPlayerImpl(
Если это репозиторий, то лучше добавить постфикс RepositoryImpl, аналогично в интерфейс

2024-08-26 04:07 UTC, DmitrijEgorow commented on app/src/main/java/com/msaggik/playlistmaker/player/domain/models/Track.kt
> +) : Parcelable, Serializable
Зачем оба?

2024-08-26 13:12 UTC, MSagGik commented
> Дмитрий, привет! Спасибо большое за подробное ревью, очень ценные замечания

Данный баг поправил, спасибо что заметил

2024-08-26 13:13 UTC, MSagGik commented on app/src/main/java/com/msaggik/playlistmaker/media/di/MediaModule.kt
> +        MediaMapper()
Дмитрий, привет! Спасибо большое за подробное ревью, очень ценные замечания

2024-08-26 14:45 UTC, MSagGik commented on app/src/main/java/com/msaggik/playlistmaker/media/di/MediaModule.kt
> +        MediaMapper()
По поводу вопроса "Почему mapper как single?", по моему так тратится меньше памяти (меньше объектов создаётся) и меньше работы для garbage коллектора (на его работу тратится время процессора), в данном объекте же нет состояний, можно обойтись и одним, если я не прав, пожалуйста поправь

2024-08-26 14:47 UTC, MSagGik commented on app/src/main/java/com/msaggik/playlistmaker/media/presentation/ui/adapters/PlaylistWithTracksAdapter.kt
> +                else -> binding.root.context.getString(R.string.number_tracks_c, model.tracks.size)
Классно, я даже не знал о такой функции, почитал, круто, теперь можно разрабатывать ещё быстрее) Спасибо Дмитрий!

2024-08-26 14:47 UTC, MSagGik commented on app/src/main/java/com/msaggik/playlistmaker/media/presentation/ui/adapters/PlaylistWithTracksAdapter.kt
> +                else -> binding.root.context.getString(R.string.number_tracks_c, model.tracks.size)
Классно, я даже не знал о такой функции 'string plurals', почитал, круто, теперь можно разрабатывать ещё быстрее) Спасибо Дмитрий!

2024-08-26 14:49 UTC, MSagGik commented on app/src/main/java/com/msaggik/playlistmaker/media/presentation/ui/adapters/PlaylistWithTracksAdapter.kt
> +                else -> binding.root.context.getString(R.string.number_tracks_c, model.tracks.size)
Классно, я даже не знал о такой функции `string plurals`, почитал, круто, теперь можно разрабатывать ещё быстрее) Спасибо Дмитрий!

2024-08-26 14:50 UTC, MSagGik commented on app/src/main/java/com/msaggik/playlistmaker/media/presentation/ui/fragments/PlaylistsFragment.kt
> +    }
Хорошо, спасибо

2024-08-26 15:38 UTC, MSagGik commented on app/src/main/java/com/msaggik/playlistmaker/player/data/repository_impl/TrackPlayerImpl.kt
>  class TrackPlayerImpl(
Абсолютно согласен, переименовал и репозитория и его реализацию

2024-08-26 15:39 UTC, MSagGik commented on app/src/main/java/com/msaggik/playlistmaker/player/data/repository_impl/TrackPlayerImpl.kt
>  class TrackPlayerImpl(
Абсолютно согласен, переименовал и репозиторий и его реализацию

2024-08-26 15:43 UTC, MSagGik commented on app/src/main/java/com/msaggik/playlistmaker/player/domain/models/Track.kt
> +) : Parcelable, Serializable
Да, сериализация тут лишняя, поправил

2024-08-27 11:23 UTC, MSagGik commented
Дмитрий, я все замечания исправил, дорабатывая код я много интересного узнал, премного благодарен тебе за столь подробное и познавательное ревью

2024-08-27 11:24 UTC, MSagGik commented
Дмитрий, я все замечания исправил, дорабатывая код много интересного узнал, премного благодарен тебе за столь подробное и познавательное ревью

2024-08-27 11:24 UTC, MSagGik commented
Дмитрий, я все замечания исправил, дорабатывая код я много интересного узнал, премного благодарен тебе за столь подробное и познавательное ревью

2024-08-28 06:56 UTC, DmitrijEgorow commented on app/src/main/java/com/msaggik/playlistmaker/media/di/MediaModule.kt
> +        MediaMapper()
Мапперы не сохраняют внутреннее состояние (stateless) и не должно быть накладно их создавать, но можно и так

2024-08-28 06:58 UTC, DmitrijEgorow commented on app/src/main/res/values/strings.xml
> +    <string name="empty_playlists">Вы не создалини одного плейлиста</string>
```suggestion
    <string name="empty_playlists">Вы не создали ни одного плейлиста</string>
```

2024-08-28 10:41 UTC, MSagGik commented on app/src/main/res/values/strings.xml
> +    <string name="empty_playlists">Вы не создалини одного плейлиста</string>
Дмитрий, приветствую! Все определённые тобой замечания я исправил, спасибо тебе большое за проработанное качественное ревью

2024-08-29 16:07 UTC, merged